### ISSUE TITLE
React warning

### ISSUE THREAD

**Issue by EmirGluhbegovic** [sautumn/material-ui-autocomplete-google-places#10]
Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

Is there any plan to update this? I see there is a pending pull request

**Comment by bmkrocks1** [comment]
I have a pending pull request for this one.
https://github.com/sautumn/material-ui-autocomplete-google-places/pull/8

**Comment by archcorsair** [comment]
This was solved thanks to @bmkrocks1 in https://github.com/sautumn/material-ui-autocomplete-google-places/pull/8

**Comment by EmirGluhbegovic** [comment]
@archcorsair Probably a noob question. I have tried to update my material-ui-autocomplete-google-places npm package but am still getting the warning? How do I make the latest commit take effect?

**Comment by bmkrocks1** [comment]
Did you already ran npm install in your project?

**Comment by EmirGluhbegovic** [comment]
Ye, ran npm remove and npm install for this package

**Comment by bmkrocks1** [comment]
Can you try the npm uninstall instead of the npm remove?

**Comment by EmirGluhbegovic** [comment]
Tried npm uninstall and npm install, still getting the warning?

**Comment by bmkrocks1** [comment]
My guess is that the latest code change was never released yet. A bump in the version in package.json is needed.

**Comment by EmirGluhbegovic** [comment]
@archcorsair  please look at @bmkrocks1  last comment

**Comment by archcorsair** [comment]
@sautumn will need to publish this to npm. Reopening until  it's published

**Comment by EmirGluhbegovic** [comment]
Great, thank you! and for helping out with this package.

**Comment by EmirGluhbegovic** [comment]
Hey Comrades, has this issue be resolved?

**Comment by archcorsair** [comment]
Apologies, the package maintainers have not been able to work on this package in some time. However there are plans for a complete rewrite & support for latest MUI 
very soon. Good luck & sorry for the inconvenience!
